version: "3"

services:
  nautilus_ps:
    container_name: "nautilus_ps"
    image: a9a9f51d6bc1
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - /home/wagao/Área de Trabalho/Linguagens de Programação/entregaveisNAUTILUS/3 - Docker/catkin_ws:/root/catkin_ws
    network_mode: host
    stdin_open: true
    tty: true
    
